---
title: Stanley McMillan
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: stanalanmcm@gmail.com
description: 'Full stack web developer <br> CSS3 HTML5 Ruby on Rails Javascript PHP
  SQL

'
baseurl: ''
url: mcmillanator.github.io
github_username: mcmillanator
markdown: kramdown
